### ISSUE TITLE
Name suggestion

### ISSUE THREAD

**Issue by green-nsk** [c42f/Contexts.jl#12]
May I suggest using `@~` instead of `@defer`?

I understand the `defer` name comes from GoLang, but it feels too generic of a name.

**Comment by c42f** [comment]
I quite like `@defer` but we could consider another sufficiently-compelling name.

I don't think `@~` is better though — it may be short but it's just completely mysterious!

**Comment by c42f** [comment]
I acknowledge that `@!` may also be considered completely mysterious :-) But it's motivated by the analogy to the proposed Base syntax.

**Comment by c42f** [comment]
Regarding genericity — I think it's appropriate to use a generic name because defer is very generic functionality. Essentially, `defer` is rather like `try...finally` with a little more flexibility.
